version: '3'

services:
  app:
    build:
      context: node
      dockerfile: Dockerfile
    networks:
      - node-network
    volumes:
      - ./node/data:/usr/src/app
    tty: true
    container_name: app
    # dockerize waits until it's possible to connect over 'TCP' to the 'db' container at the port '3306'
    entrypoint: dockerize --wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    tty: true
    depends_on:
      - app

networks:
  node-network:
    driver: bridge